### ISSUE TITLE
Assignment :: User Service

### ISSUE THREAD

**Issue by up1** [up1/soa_group8#1]
* Remove => .settings, .classpath, .project
* Move insert statement to data.sql
* ???
```
int start = (int)(Math.max((page - 1), 0) * limit);
```

**Comment by it57070078** [comment]
ใช้สำหรับการ Skip ผลการค้นหาตอนสั่งคิวรี่คำสั่ง SQL 
ตัวอย่างเช่น
ถ้าเกิดเรียก Page = 2 มันก็จะสามารถ Skip ผลการค้นหาไปยังรายการที่ 10 โดยเอา item_per_page มาคำนวน

**Comment by up1** [comment]
+ please fix this issue, 
and after fixed, please close this issue

**Comment by tytleteerachart** [comment]
Bug fixes:
- Fixed getAllUser method in UserController class by changing parameter type to int
- Fixed findAll method in UserRepository class by using LIMIT and OFFSET in SQL
- Add constructor in UserNotFoundException class
- Fixed schema.sql by moving insert SQL command to data.sql
